[package]
name = "mdns"
version = "0.2.2"
authors = ["Dylan McKay <me@dylanmckay.io>"]

description = """
A multicast DNS client library.

Supports discovery of any mDNS device on a LAN.
"""

license = "MIT"
documentation = "https://docs.rs/mdns"
repository = "https://github.com/dylanmckay/mdns"

categories = ["network-programming"]
keywords = ["mdns", "dns", "multicast", "chromecast", "discovery"]

[dependencies]
mio = "0.6"
dns-parser = "0.7"
net2 = "0.2"
error-chain = "0.11"

[target.'cfg(target_family="unix")'.dependencies]
ifaces = "0.1.0"

[target.'cfg(target_family="windows")'.dependencies]
ipconfig = { git = "https://github.com/glebpom/ipconfig.git", rev = "mask"}
